---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 20/12/2019 19:07
---
--[[RageUI Stuff]]
players = {}

selectedPlayer = {}

players = {}
RMenu.Add('nhsmenu', 'main', RageUI.CreateMenu(cfg.langs[cfg.lang].title, cfg.langs[cfg.lang].subtitle))          -- ("NHS Interaction", "Undefined for using SetSubtitle"))
RMenu:Get('nhsmenu', 'main').EnableMouse = false
RMenu:Get('nhsmenu', 'main').Closed = function()
RMenu.Add("nhsmenu", "subMenu", RageUI.CreateSubMenu(RMenu:Get("nhsmenu", "main")))
selectedPlayer = {}

RageUI.CreateWhile(
    1.0,
    RMenu:Get("nhsmenu", "main"),
    nil,
    function()
        RageUI.IsVisible(
            RMenu:Get("nhsmenu", "main"),
            true,
            true,
            true,
            function()
                for k, v in pairs(players) do
                    RageUI.Button(
                        "[" .. v[2] .. "] " .. v[1],
                        "Name: " .. v[1] .. " User ID: " .. v[3] .. " Server ID: " .. v[2],
                        {RightLabel = ">>>"},
                        true,
                        function(Hovered, Active, Selected)
                            if Selected then
                                RMenu:Get("nhsmenu", "subMenu"):SetTitle(v[1])
                                RMenu:Get("nhsmenu", "subMenu"):SetSubtitle(
                                    "Name: " .. v[1] .. " User ID: " .. v[3] .. " Server ID: " .. v[2]
                                )
                                selectedPlayer = players[k]
                            end
                        end,
                        RMenu:Get("nhsmenu", "subMenu")
                    )
                end
            end,
            function()
            end
        )
    end
)

RegisterNetEvent("TBRP:SendPlayersInfo")
AddEventHandler(

    "TBRP:SendPlayersInfo",
    function(players_table, btns)
        players = players_table
        buttons = btns
        RageUI.Visible(RMenu:Get("nhsmenu", "main"), not RageUI.Visible(RMenu:Get("nhsmenu", "main")))
    end
)

Citizen.CreateThread(
   function()
    while true do
        Citizen.Wait(0)
        if isControlJustPressed(1, cfg.key) then
            TriggerServerEvent("TBRP:GetPlayerInformation")
          end
      end
  end

)

---[[Buttons]]

function revPlayerBtn(player)
    RageUI.Button(
        cfg.langs[cfg.lang].revPlayer,
        cfg.langs[cfg.lang].revPlayerDesc,
        {
            LeftBadge = nil,
            RightBadge = nil,
            RightLabel = nil
        },
        true,
        function(Hovered, Active, Selected)
            if Selected then
                TriggerServerEvent("TBRP:REVIVE", player[2])
            end
            if Hovered then
            -- My action the button is hovered by the mouse
            end
            if Active then
            -- My action the button is hightlighted
            end
        end
    )
end
function putinvehPlayerBtn(player)
    RageUI.Button(
        cfg.langs[cfg.lang].putinvehPlayer,
        cfg.langs[cfg.lang].putinvehPlayerDesc,
        {
            LeftBadge = nil,
            RightBadge = nil,
            RightLabel = nil
        },
        true,
        function(Hovered, Active, Selected)
            if Selected then
                TriggerServerEvent("TBRP:PUTINVEH", player[2])
            end
            if Hovered then
            -- My action the button is hovered by the mouse
            end
            if Active then
            -- My action the button is hightlighted
            end
        end
    )
end
function getoutvehPlayerBtn(player)
    RageUI.Button(
        cfg.langs[cfg.lang].getoutvehPlayer,
        cfg.langs[cfg.lang].getoutvehPlayerDesc,
        {
            LeftBadge = nil,
            RightBadge = nil,
            RightLabel = nil
        },
        true,
        function(Hovered, Active, Selected)
            if Selected then
                TriggerServerEvent("TBRP:GETOUTVEH", player[2])
            end
            if Hovered then
            -- My action the button is hovered by the mouse
            end
            if Active then
            -- My action the button is hightlighted
        end
    end
)
end
end