local cfg = {}

-- define each group with a set of permissions
-- _config property:
--- gtype (optional): used to have only one group with the same gtype per player (example: a job gtype to only have one job)
--- onspawn (optional): function(player) (called when the player spawn with the group)
--- onjoin (optional): function(player) (called when the player join the group)
--- onleave (optional): function(player) (called when the player leave the group)
--- (you have direct access to vRP and vRPclient, the tunnel to client, in the config callbacks)

cfg.groups = {
  ["Founder"] = {
    _config = {onspawn = function(player) vRPclient.notify(player,{"You are Founder."}) end},
    "player.group.add",
    "player.group.add.superadmin",
    "player.group.add.admin",  --- this is just a example which can be added to admin/mod group if being made
    "player.group.remove",
    "player.givemoney",
	"player.giveitem",
	"player.givebank",
	"player.givecash"
  },
  ["superadmin"] = {
 	"player.group.add",
  	"player.group.remove",
    "admin.tickets",
    "admin.announce",
	"admin.menu",
	"admin.easy_unjail",
	"admin.spawnveh",
	"admin.deleteveh",
	"player.blips",
	"player.tptowaypoint",
    "player.list",
    "player.whitelist",
    "player.unwhitelist",
    "player.kick",
    "player.ban",
    "player.unban",
    "player.noclip",
    "player.custom_emote",
    "player.custom_sound",
    "player.display_custom",
    "player.coords",
    "player.tptome",
	"emergency.revive",
	"emergency.shop",
	"player.tpto",
	"player.revive"
  },
  ["admin"] = {
    "admin.tickets",
    "admin.announce",
	"admin.menu",
	"admin.easy_unjail",
	-- "admin.godmode",
	"admin.spawnveh",
	"admin.deleteveh",
	"player.blips",
	"player.tptowaypoint",
    "player.list",
    "player.whitelist",
    "player.unwhitelist",
    "player.kick",
    "player.ban",
    "player.unban",
    "player.noclip",
    "player.custom_emote",
    "player.custom_sound",
    "player.display_custom",
    "player.coords",
    "player.tptome",
	"emergency.revive",
	"emergency.shop",
	"player.tpto",
	"player.revive"
  },
  ["mod"] = {
	"admin.tickets",
    "admin.announce",
    "player.list",
    "player.kick",
    "player.coords",
    "player.tptome",
	"emergency.revive",
	"emergency.shop",
    "player.tpto"
  },
  -- the group user is auto added to all logged players
  ["user"] = {
    "player.phone",
    "player.calladmin",
	"player.fix_haircut",
	"player.check",
	--"mugger.mug",
    "police.askid",
    "police.store_weapons",
	"player.skip_coma",
	"player.store_money",
	"player.check",
	"player.loot",
	"player.player_menu",
	"player.userlist",
    "police.seizable",	-- can be seized
	"user.paycheck",
	"player.loadshop"
  },
  ["Chief Medical Officer"] = {
    _config = { gtype = "job",
	onjoin = function(player) vRPclient.notify(player,{"You are now clocked on as a ~g~Chief Medical Officer~g~ ~s~ ~n~ Salary: ~g~£75,000~g~"}) end
	},
    "emergency.revive",
	"police.pc",
	--"police.wanted",
    "emergency.shop",
    "emergency.service",
	"emergency.cloakroom",
	"emscheck.revive",
	"emergency.vehicle",
	"emergency.market",
	"ems.whitelisted",
	"ems.loadshop",
	"police.putinveh",
	"police.getoutveh",
	--"player.list",
	"police.menu_interaction",
	"nhschief.paycheck",
	"player.blips",
	"ems.mission"
  },
  ["Deputy Chief Medical Officer"] = {
    _config = { gtype = "job",
	onjoin = function(player) vRPclient.notify(player,{"You are now clocked on as a ~g~Deputy Chief Medical Officer~g~ ~s~ ~n~ Salary: ~g~£65,000~g~"}) end
	},
    "emergency.revive",
	"police.pc",
	--"police.wanted",
    "emergency.shop",
    "emergency.service",
	"emergency.cloakroom",
	"emergency.vehicle",
	"emergency.market",
	"emscheck.revive",
	"ems.whitelisted",
	"ems.loadshop",
	"police.putinveh",
	"emergency.getoutveh",
	--"player.list",
	"police.menu_interaction",
	"nhsdeputy.paycheck",
	"player.blips",
	"ems.mission"
  },
  ["Asst. Chief Medical Officer"] = {
    _config = { gtype = "job",
	onjoin = function(player) vRPclient.notify(player,{"You are now clocked on as an ~g~Assistant Chief Medical Officer~g~ ~s~ ~n~ Salary: ~g~£60,000~g~"}) end
	},
    "emergency.revive",
	"police.pc",
	--"police.wanted",
    "emergency.shop",
    "emergency.service",
	"emergency.cloakroom",
	"emscheck.revive",
	"emergency.vehicle",
	"emergency.market",
	"ems.whitelisted",
	"ems.loadshop",
	"police.putinveh",
	"police.getoutveh",
	--"player.list",
	"police.menu_interaction",
	"nhsassistant.paycheck",
	"player.blips",
	"ems.mission"
  },
  ["Captain"] = {
    _config = { gtype = "job",
	onjoin = function(player) vRPclient.notify(player,{"You are now clocked on as a ~g~Captain~g~ ~s~ ~n~ Salary: ~g~£50,000~g~"}) end
	},
    "emergency.revive",
	"police.pc",
	--"police.wanted",
    "emergency.shop",
    "emergency.service",
	"emergency.cloakroom",
	"emscheck.revive",
	"emergency.vehicle",
	"emergency.market",
	"ems.whitelisted",
	"police.putinveh",
	"police.getoutveh",
	"ems.loadshop",
	--"player.list",
	"police.menu_interaction",
	"nhscaptain.paycheck",
	"player.blips",
	"ems.mission"
  },
  ["Consultant"] = {
    _config = { gtype = "job",
	onjoin = function(player) vRPclient.notify(player,{"You are now clocked on as a ~g~Consultant~g~ ~s~ ~n~ Salary: ~g~£45,000~g~"}) end
	},
    "emergency.revive",
	"police.pc",
	--"police.wanted",
    "emergency.shop",
    "emergency.service",
	"emergency.cloakroom",
	"emscheck.revive",
	"emergency.vehicle",
	"emergency.market",
	"ems.whitelisted",
	"ems.loadshop",
	"police.putinveh",
	"police.getoutveh",
	--"player.list",
	"police.menu_interaction",
	"nhsconsultant.paycheck",
	"player.blips",
	"ems.mission"
  },
  ["Senior Doctor"] = {
    _config = { gtype = "job",
	onjoin = function(player) vRPclient.notify(player,{"You are now clocked on as a ~g~Senior Doctor~g~ ~s~ ~n~ Salary: ~g~£40,000~g~"}) end
	},
    "emergency.revive",
	"police.pc",
	--"police.wanted",
    "emergency.shop",
    "emergency.service",
	"emergency.cloakroom",
	"emscheck.revive",
	"emergency.vehicle",
	"emergency.market",
	"ems.whitelisted",
	"ems.loadshop",
	"police.putinveh",
	"police.getoutveh",
	--"player.list",
	"police.menu_interaction",
	"nhsseniordoctor.paycheck",
	"player.blips",
	"ems.mission"
  },
  ["Doctor"] = {
    _config = { gtype = "job",
	onjoin = function(player) vRPclient.notify(player,{"You are now clocked on as a ~g~Doctor~g~ ~s~ ~n~ Salary: ~g~£35,000~g~"}) end
	},
    "emergency.revive",
	"police.pc",
	--"police.wanted",
    "emergency.shop",
    "emergency.service",
	"emergency.cloakroom",
	"emscheck.revive",
	"emergency.vehicle",
	"emergency.market",
	"ems.whitelisted",
	"ems.loadshop",
	"police.putinveh",
	"police.getoutveh",
	--"player.list",
	"police.menu_interaction",
	"nhsdoctor.paycheck",
	"player.blips",
	"ems.mission"
  },
  ["Junior Doctor"] = {
    _config = { gtype = "job",
	onjoin = function(player) vRPclient.notify(player,{"You are now clocked on as a ~g~Junior Doctor~g~ ~s~ ~n~ Salary: ~g~£30,000~g~"}) end
	},
    "emergency.revive",
	"police.pc",
	--"police.wanted",
    "emergency.shop",
    "emergency.service",
	"emergency.cloakroom",
	"emscheck.revive",
	"emergency.vehicle",
	"emergency.market",
	"ems.whitelisted",
	"ems.loadshop",
	"police.putinveh",
	"police.getoutveh",
	--"player.list",
	"police.menu_interaction",
	"nhsjuniordoctor.paycheck",
	"player.blips",
	"ems.mission"
  },
  ["Paramedic"] = {
    _config = { gtype = "job",
	onjoin = function(player) vRPclient.notify(player,{"You are now clocked on as a ~g~Paramedic~g~ ~s~ ~n~ Salary: ~g~£25,000~g~"}) end
	},
    "emergency.revive",
	"police.pc",
	--"police.wanted",
    "emergency.shop",
    "emergency.service",
	"emergency.cloakroom",
	"emscheck.revive",
	"emergency.vehicle",
	"emergency.market",
	"ems.whitelisted",
	"ems.loadshop",
	"police.putinveh",
	"police.getoutveh",
	--"player.list",
	"police.menu_interaction",
	"nhsparamedic.paycheck",
	"player.blips",
	"ems.mission"
  },
  ["Trainee Paramedic"] = {
    _config = { gtype = "job",
	onjoin = function(player) vRPclient.notify(player,{"You are now clocked on as a ~g~Trainee Paramedic~g~ ~s~ ~n~ Salary: ~g~£20,000~g~"}) end
	},
    "emergency.revive",
	"police.pc",
	--"police.wanted",
    "emergency.shop",
    "emergency.service",
	"emergency.cloakroom",
	"emscheck.revive",
	"emergency.vehicle",
	"emergency.market",
	"ems.whitelisted",
	"ems.loadshop",
	"police.putinveh",
	"police.getoutveh",
	--"player.list",
	"police.menu_interaction",
	"nhstrainee.paycheck",
	"player.blips",
	"ems.mission"
  },
  ["Unemployed"] = {
    _config = { gtype = "job",
	onspawn = function(player) vRPclient.notify(player,{"You are Unemployed, go to Department of Jobs."}) end
	},
	"citizen.paycheck",
	"player.loadshop"
  },
  ["Commissioner"] = {
    _config = { gtype = "job",
	onjoin = function(player) vRPclient.notify(player,{"You are now clocked on as a ~g~Commissioner~g~ ~s~ ~n~ Salary: ~g~£130,000~g~"}) end
	},
	"police.cloakroom",
    "police.pc",
	"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.onduty",
    "police.announce",
   -- "-police.store_weapons",
    "-police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"Cadet.vehicle",
	"police.loadshop",
	"cop.whitelisted",
	"commissioner.paycheck",
	"police.menu_interaction",
	"police.mission",
	"police.doors"
  },
  ["Dep. Commissioner"] = {
    _config = { gtype = "job",
	onjoin = function(player) vRPclient.notify(player,{"You are now clocked on as a ~g~Dep. Commissioner~g~ ~s~ ~n~ Salary: ~g~£120,000~g~"}) end
	},
	"police.cloakroom",
    "police.pc",
	"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.onduty",
    "police.announce",
   -- "-police.store_weapons",
    "-police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"depcommissioner.paycheck",
	"police.menu_interaction",
	"police.mission",
	"police.doors"
  },
  ["Ass. Commissioner"] = {
    _config = { gtype = "job",
	onjoin = function(player) vRPclient.notify(player,{"You are now clocked on as a ~g~Ass. Commissioner~g~ ~s~ ~n~ Salary: ~g~£115,000~g~"}) end
	},
	"police.cloakroom",
    "police.pc",
	"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.onduty",
    "police.announce",
    --"-police.store_weapons",
    "-police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"asscommissioner.paycheck",
	"police.menu_interaction",
	"police.mission"
  },
  ["Chief Superintendent"] = {
    _config = { gtype = "job",
	onjoin = function(player) vRPclient.notify(player,{"You are now clocked on as a ~g~Chief Superintendent~g~ ~s~ ~n~ Salary: ~g~£70,000~g~"}) end
	},
	"police.cloakroom",
    "police.pc",
	"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.onduty",
    "police.announce",
   -- "-police.store_weapons",
    "-police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"Bounty.vehicle",
	"Bounty.loadshop",
	"police.menu_interaction",
	"cop.whitelisted",
	"chiefsuperintendent.paycheck",
  },
  ["Superintendent"] = {
	_config = { gtype = "job",
	onjoin = function(player) vRPclient.notify(player,{"You are now clocked on as a ~g~Superintendent~g~ ~s~ ~n~ Salary: ~g~£60,000~g~"}) end
	},
	"police.cloakroom",
    "police.pc",
	"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.onduty",
    "police.announce",
   -- "-police.store_weapons",
    "-police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"superintendent.paycheck",
	"police.menu_interaction",
	"police.mission"
  },
  ["Chief Inspector"] = {
	_config = { gtype = "job",
	onjoin = function(player) vRPclient.notify(player,{"You are now clocked on as a ~g~Chief Inspector~g~ ~s~ ~n~ Salary: ~g~£50,000~g~"}) end
	},
	"police.cloakroom",
    "police.pc",
	"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.onduty",
    "police.announce",
    --"-police.store_weapons",
    "-police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"chiefinspector.paycheck",
	"police.menu_interaction",
	"police.mission"
  },
    ["Inspector"] = {
	_config = { gtype = "job",
	onjoin = function(player) vRPclient.notify(player,{"You are now clocked on as a ~g~Inspector~g~ ~s~ ~n~ Salary: ~g~£45,000~g~"}) end
	},
	"police.cloakroom",
    "police.pc",
	"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.onduty",
    "police.announce",
   -- "-police.store_weapons",
    "-police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"inspector.paycheck",
	"police.menu_interaction",
	"police.mission"
  },
	["Sergeant"] = {
	_config = { gtype = "job",
	onjoin = function(player) vRPclient.notify(player,{"You are now clocked on as a ~g~Sergeant~g~ ~s~ ~n~ Salary: ~g~£40,000~g~"}) end
	},
	"police.cloakroom",
    "police.pc",
	"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.onduty",
    "police.announce",
   -- "-police.store_weapons",
    "-police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"sergeant.paycheck",
	"police.menu_interaction",
	"police.mission"
  },
    ["Senior Constable"] = {
	_config = { gtype = "job",
	onjoin = function(player) vRPclient.notify(player,{"You are now clocked on as a ~g~Senior Constable~g~ ~s~ ~n~ Salary: ~g~£30,000~g~"}) end
	},
	"police.cloakroom",
    "police.pc",
	"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.onduty",
    "police.announce",
   -- "-police.store_weapons",
    "-police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"seniorconstable.paycheck",
	"police.menu_interaction",
	"police.mission"
  },
      ["Police Constable"] = {
	_config = { gtype = "job",
	onjoin = function(player) vRPclient.notify(player,{"You are now clocked on as a ~g~Police Constable~g~ ~s~ ~n~ Salary: ~g~£20,000~g~"}) end
	},
	"police.cloakroom",
    "police.pc",
	"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.onduty",
    "police.announce",
   -- "-police.store_weapons",
    "-police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"policeconstable.paycheck",
	"police.menu_interaction",
	"police.mission"
  },
    ["PCSO"] = {
	_config = { gtype = "job",
	onjoin = function(player) vRPclient.notify(player,{"You are now clocked on as a ~g~PCSO~g~ ~s~ ~n~ Salary: ~g~£15,000~g~"}) end
	},
	"police.cloakroom",
    "police.pc",
	"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.onduty",
    "police.announce",
   -- "-police.store_weapons",
    "-police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"nhs.menu",
	"cop.whitelisted",
	"pcso.paycheck",
	"police.menu_interaction",
	"police.mission"
  },
  
  -- whitelist group for police, emergency and president jobs / add player to this group and user can view the job selection / search in the map
  -- moderator=president / president is guy from the server give a player group cop ems moderator when admin is offline / sallary : $10.000
  ["gc"] = {
    "player.group.add.cop",
    "player.group.remove.cop",
    "player.group.add.trident",
    "player.group.remove.trident",
    "gc.whitelisted",
    "trident.whitelisted",
    "cop.whitelisted"
  },
  ["trident"] = {
    "trident.whitelisted",
    "cop.whitelisted"
  },
  ["cop"] = {
    "cop.whitelisted"
  },
  ["nhs2"] = {
    "player.group.add.nhs",
    "player.group.remove.nhs",
    "nhs.whitelisted"
  },
  ["nhs"] = {  
    "nhs.whitelisted"
  }
}

-- groups are added dynamically using the API or the menu, but you can add group when an user join here
cfg.users = {
  [1] = { -- give superadmin and admin group to the first created user on the database
    "superadmin",
    "admin"
  }
}

-- group selectors
-- _config
--- x,y,z, blipid, blipcolor, permissions (optional)

cfg.selectors = {
  ["Job Center"] = {
    _config = {x = -552.76818847656, y = -190.54847717285, z = 41.365055084229, blipid = 351, blipcolor = 47},
    "Unemployed"
	},
  ["Police Station"] = { -- Alta Street
    _config = {x = 447.35137939453, y = -975.57592773438, z = 30.689584732056, blipid = 351, blipcolor = 38, permissions = {"cop.whitelisted"} }, 
	"PCSO",
	"Police Constable",
	"Senior Constable",
	"Sergeant",
	"Inspector",
	"Chief Inspector",
	"Superintendent",
	"Chief Superintendent",
	"Ass. Commissioner",
	"Dep. Commissioner",
	"Commissioner",
	"Unemployed"
	},
  ["NHS"] = { -- Spawn Hospital
    _config = {x =  308.61538696289, y = -601.9326171875, z = 43.283977508545, blipid = 351, blipcolor = 3, permissions = {"nhs.whitelisted"} },
    "Chief Medical Officer",
    "Deputy Chief Medical Officer",
    "Asst. Chief Medical Officer",
    "Captain",
    "Consultant",
    "Senior Doctor",
    "Doctor",
    "Junior Doctor",
    "Paramedic",
    "Trainee Paramedic",
    "Unemployed"
  }
}

return cfg
 