
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('battery', 'Car Battery', '2', '0', '1');
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('aluminium', 'Scrap Aluminium', '1', '0', '1');
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('radio', 'Car Stereo', '3', '0', '1');
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('airbag', 'Airbag', '1', '0', '1');
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('wheel_rim', 'Wheel Rim', '1', '0', '1');